### ISSUE TITLE
Divide preClose() of AbstractWizardStep to "Previous Button clicked" and  "Next Button clicked"

### ISSUE THREAD

**Issue by nicokowalczyk** [mariodavid/cuba-component-wizard#20]
I want to validate the fields of one step only if next button is clicked. 
Right now it is not possible to react only on the click of "next"-button.

**Comment by nicokowalczyk** [comment]
@mariodavid 
Hi Mario,
kannst du dir mal anschauen, ob die Änderung sinnig ist? Es gibt auch schon einen Pull-Request dafür.

VG Nico

**Comment by mariodavid** [comment]
Hi,

Will answer in english, so that other people can also read the conversation :)

Thanks for the issue and PR. Perhaps you can elaborate a little bit on how thhe usage looks like? Perhaps i'm just missing the context a little. What peoblem does it solve?

Probably it also helps to know the use case when thinking about doing an implementation on the modern CUBA 7 UI APIs.

Thanks
Mario

**Comment by mariodavid** [comment]
Hi,

I just released version 0.8.0 which supports CUBA 7 based Screen APIs as well as the use-case you described with the possibility to identify which button was clicked.

Please try with the new version. I will close this for now.

Cheers
Mario
